### ISSUE TITLE
Display Managers known to work

### ISSUE THREAD

**Issue by WasteOfO2** [hyprwm/hyprland-wiki#147]
Hey,  I am planning on making a page for Display Managers Known to work. The ones I have tested so far are SDDM, greetd and ly

Requesting further input from others

**Comment by jakbie10** [comment]
this is what I got from gdb
```
(gdb) file /usr/local/bin/Hyprland
Reading symbols from /usr/local/bin/Hyprland...
(No debugging symbols found in /usr/local/bin/Hyprland)
(gdb) core Hyprland.core
[New LWP 100792]
warning: Could not load shared library symbols for [vdso].
Do you need "set solib-search-path" or "set sysroot"?
Core was generated by `Hyprland'.
Program terminated with signal SIGABRT, Aborted.
Sent by thr_kill() from pid 1128 and user 1001.
#0  0x000000082cccbc5a in thr_kill () from /lib/libc.so.7
(gdb) bt
#0  0x000000082cccbc5a in thr_kill () at /lib/libc.so.7
#1  0x000000082cc446d4 in raise () at /lib/libc.so.7
#2  0x000000082ccf5a59 in abort () at /lib/libc.so.7
#3  0x000000082acbce39 in  () at /lib/libcxxrt.so.1
#4  0x00000000002daf05 in main ()
```

**Comment by Enigma1309** [comment]
Almost every display manager works and something like that already exists in [Master tutorial](https://wiki.hyprland.org/Getting-Started/Master-Tutorial/)


Anyways the display managers i've used with hyprland are :-

- GDM - Gnome Display Manager
- SDDM (Already mentioned)

**Comment by svenstaro** [comment]
This issue should likely be closed as this section does indeed exist in the tutorial.
